spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reviewProject
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


logging.level:
  org.hibernate.SQL: debug